version: '3.9'
services:
  salt_master:
    build: 
      context: .
      dockerfile: Dockerfile.inventory
      args:
        - soundfleet_url=${SOUNDFLEET_URL}
    networks:
      - default
    ports:
      - '4505-4506:4505-4506'
      - '8001:8001'
    environment:
      SALT_API_CONFIG: > 
        {
          "rest_cherrypy": {
            "port": 8001,
            "disable_ssl": true
          },
          "external_auth": {
            "sharedsecret": {
              "saltdev": [
                ".*",
                "@wheel",
                "@runner",
                "@jobs"
              ]
            }
          },
          "sharedsecret": "saltpass"
        }

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=soundfleet
      - POSTGRES_USER=soundfleet
      - POSTGRES_PASSWORD=soundfleet
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - default

  soundfleet:
    build: 
      context: .
      dockerfile: Dockerfile.soundfleet
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - assets:/assets
      - caches:/caches
    networks:
      - default
    environment:
      - DATABASE_URL=postgresql://soundfleet:soundfleet@db:5432/soundfleet
      - MEDIA_ROOT=/assets/media/
      - DOMAIN=${DOMAIN}
      - CORS_ORIGIN_WHITELIST=${CORS_ORIGIN_WHITELIST}

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
      args:
        - soundfleet_url=${SOUNDFLEET_URL}
    ports:
      - 3000:3000
    networks:
      - default

  worker:
    build: 
      context: .
      dockerfile: Dockerfile.soundfleet
    depends_on:
      - db
      - rabbitmq
    volumes:
      - assets:/assets
      - caches:/caches
    networks:
      - default
    environment:
      - DATABASE_URL=postgresql://soundfleet:soundfleet@db:5432/soundfleet
      - MEDIA_ROOT=/assets/media/
      - DOMAIN=${DOMAIN}
    command: celery -A soundfleet worker

volumes:
  db:
  assets:
  caches:
