FROM node:19-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY soundfleet-dashboard ./

RUN npm install 

ARG soundfleet_url

RUN echo "REACT_APP_API_URL=$soundfleet_url/api" > .env.development

CMD ["npm", "start"]