FROM python:3.10-slim-bullseye

RUN apt update -y
RUN apt install -y gcc ffmpeg libmagic1

COPY . /app

RUN pip install -r /app/requirements.txt
RUN pip install -r /app/requirements.dev.txt

WORKDIR /app

EXPOSE 8000

CMD ./manage.py runserver 0.0.0.0:8000